baseURL = "http://www.uncommonhacks.github.io/blog/"
languageCode = "en-us"
title = "Uncommon Blog"
theme = "hugridway"
contentdir = "content"
layoutdir = "layouts"
publishdir = "docs"

[params]
background = "#EF6398"
palette = ["#8968AC","#EEE365","#82D2E6","#EFA02E","#89CDB7","#67B9E7"]
