baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hugridway"
contentdir = "content"
layoutdir = "layouts"
publishdir = "docs"

[params]
background = "#EF6398"
palette = ["#8968AC","#EEE365","#82D2E6","#EFA02E","#89CDB7","#67B9E7"]
